#!/usr/bin/env bash

###########
# STARTUP #
###########

# keybinding daemon
sxhkd &

# window compositor
picom -b --config $HOME/.config/picom/picom.conf &

# prevents middle click paste in terminal because it's annoying
xmousepasteblock &

# set wallpaper
nitrogen --set-scaled $HOME/wallpaper.png

# polybar
$HOME/.config/polybar/launch.sh > /dev/null 2> $HOME/.polybar.log &

# polybar height
bspc config top_padding 40

xsetroot -cursor_name left_ptr

################
# bspwm config #
################

# 2 monitors
if [[ "$( xrandr -q | grep -w "connected" | wc -l )" -eq "2" ]]; then
    xrandr --output "HDMI-1" --primary --mode "1920x1080" --rotate normal --output "HDMI-2" --mode "1920x1080" --rotate normal --left-of "HDMI-1"
    
    bspc monitor "HDMI-1" -d 1 2 3 4 5
    bspc monitor "HDMI-2" -d 6 7 8 9 10
else
    bspc monitor -d 1 2 3 4 5 6
fi

bspc config border_width 2
bspc config window_gap   6

# Border colors
bspc config normal_border_color  "$(xrdb -get color0)"
bspc config focused_border_color "$(xrdb -get color4)"
bspc config presel_feedback_color  "$(xrdb -get color8)"

bspc config split_ratio        0.50
bspc config borderless_monocle true
bspc config gapless_monocle    true

