#!/usr/bin/env bash

###########
# STARTUP #
###########

# keybinding daemon
sxhkd &

# window compositor
picom -b --config $HOME/.config/picom/picom.conf &

# prevents middle click paste in terminal because it's annoying
xmousepasteblock &

# keyboard layouts
setxkbmap us,cz -option 'grp:alt_shift_toggle'

# 2 monitors
if [[ "$( xrandr -q | grep -w "connected" | wc -l )" -gt "1" ]]; then
    
    xrandr --output "HDMI-0" --off
    xrandr --output "HDMI-1" --off

    xrandr --output "HDMI-0" --primary --mode "1920x1080" --rotate normal --output "HDMI-1" --mode "1920x1080" --rotate normal --left-of "HDMI-0"

    # set wallpaper
    nitrogen --head=0 --set-scaled $HOME/wallpaper.png
    nitrogen --head=1 --set-scaled $HOME/wallpaper.png

    bspc monitor "HDMI-0" -d 1 2 3 4 5
    bspc monitor "HDMI-1" -d 6 7 8 9 10

else
    bspc monitor -d 1 2 3 4 5 6
    # set wallpaper
    nitrogen --head=0 --set-scaled $HOME/wallpaper.png
fi

# polybar
$HOME/.config/polybar/launch.sh > /dev/null 2> $HOME/.polybar.log &

# polybar height
bspc config top_padding 40

xsetroot -cursor_name left_ptr

################
# bspwm config #
################

bspc config border_width 2
bspc config window_gap   4

# Border colors
bspc config normal_border_color  "$(xrdb -get color0)"
bspc config focused_border_color "$(xrdb -get color4)"
bspc config presel_feedback_color  "$(xrdb -get color8)"

bspc config split_ratio        0.50
bspc config borderless_monocle true
bspc config gapless_monocle    true

