require("plugins.lsp")
require("plugins.telescope")
require("plugins.cmp")
require("plugins.nvim-tree")
require("plugins.lualine")
require("plugins.treesitter")
require("plugins.barbar")
require("plugins.gitsigns")
